apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomoteadmin
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfomoteadmin/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfomoteadmin/internal/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1536Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfomoteadmin/internal/prometheus
  ingresses:
    - "https://syfomoteadmin.dev.intern.nav.no"
    - "https://syfomoteadmin.nais.preprod.local"
    - "https://app-q1.adeo.no/syfomoteadmin"
    - "https://syfomoteadmin.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfomoteadmin.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/dev/creds/moteadmin_q1-user"
        mountPath: "/secrets/moteadmindb/credentials"
      - kvPath: "/oracle/data/dev/config/moteadmin_q1"
        mountPath: "/secrets/moteadmindb/config"
      - kvPath: "/serviceuser/data/dev/srvsyfomoteadmin"
        mountPath: "/secrets/serviceuser/syfomoteadmin"
      - kvPath: "serviceuser/data/dev/srvssolinux"
        mountPath: "/secrets/ldap/ldap"
      - kvPath: "/kv/preprod/fss/syfomoteadmin/default"
        mountPath: "/var/run/secrets/nais.io/vault"
  leaderElection: true
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: MODAPP_URL
      value: https://modapp-q1.adeo.no
    - name: TJENESTER_URL
      value: https://tjenester-q1.nav.no
    - name: TOGGLE_ENABLE_BATCH_PAAMINNELSE
      value: 'true'
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SMTPSERVER_HOST
      value: smtp.preprod.local
    - name: SMTPSERVER_PORT
      value: '25'
    - name: MQGATEWAY03_HOSTNAME
      value: b27apvl221.preprod.local
    - name: MQGATEWAY03_PORT
      value: '1413'
    - name: MQGATEWAY03_NAME
      value: MQLS03
    - name: SYFOMOTEADMIN_CHANNEL_NAME
      value: Q1_SYFOMOTEADMIN
    - name: SERVICEVARSEL_QUEUENAME
      value: QA.Q1_VARSELPRODUKSJON.SEND_VARSEL
    - name: TREDJEPARTSVARSEL_QUEUENAME
      value: QA.Q1_VARSELPRODUKSJON.BEST_SRVMLD_M_KONTAKT
    - name: NO_NAV_SECURITY_OIDC_ISSUER_STS_DISCOVERYURL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: NO_NAV_SECURITY_OIDC_ISSUER_STS_ACCEPTEDAUDIENCE
      value: srvsyfomotebehov,srvsyfoservice
    - name: AXSYS_URL
      value: "https://axsys.nais.preprod.local"
    - name: DKIF_URL
      value: "https://dkif.nais.preprod.local"
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.dev.intern.nav.no"
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.nais.preprod.local
    - name: ISNARMESTELEDER_HOST
      value: "https://isnarmesteleder.dev.intern.nav.no"
    - name: ISNARMESTELEDER_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: KAFKA_ENV_NAME
      value: q1
