no.nav.security.oidc:
  issuers: selvbetjening,veileder,sts
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      cookie_name: selvbetjening-idtoken
    veileder:
      discoveryurl: <SETTES FRA MILJØCONFIG>
      accepted_audience: <SETTES FRA MILJØCONFIG>
      cookie_name: isso-idtoken
    veilederaad:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token
    sts:
      discoveryurl: <SETTES FRA MILJØCONFIG>
      accepted_audience: <SETTES FRA MILJØCONFIG>

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfomoteadmin

spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8
  kafka:
    client-id: ${nais.app.name}-${kafka.env.name}
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${srv.username}" password="${srv.password}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

dev: false
