-- ROLLBACK-START
------------------
-- ALTER TABLE MOTE
--   DROP CONSTRAINT TID_STED_M_FK;
-- DROP SEQUENCE TID_STED_ID_SEQ;
-- DROP SEQUENCE MOTEDELTAKER_ID_SEQ;
-- DROP SEQUENCE MOTE_ID_SEQ;
-- DROP SEQUENCE MOTETYPE_ID_SEQ;
-- DROP TABLE MOTETYPE;
-- DROP TABLE AVSLAG;
-- DROP TABLE MOTEDELTAKER_TID_STED;
-- DROP TABLE TID_STED;
-- DROP TABLE MOTEDELTAKER_ARBEIDSGIVER;
-- DROP TABLE MOTEDELTAKER_AKTORID;
-- DROP TABLE MOTEDELTAKER;
-- DROP TABLE MOTE;
---------------
-- ROLLBACK-END

CREATE SEQUENCE MOTE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MOTE (
  mote_id           NUMBER(19, 0)       NOT NULL,
  mote_uuid         VARCHAR(255) UNIQUE NOT NULL,
  opprettet_av      VARCHAR(255)        NOT NULL,
  nav_enhet         VARCHAR(255)        NOT NULL,
  created           TIMESTAMP           NOT NULL,
  valgt_tid_sted_id NUMBER(19, 0),
  CONSTRAINT MOTE_PK PRIMARY KEY (mote_id)
);

CREATE SEQUENCE MOTETYPE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MOTETYPE (
  motetype_id NUMBER(19, 0) NOT NULL,
  mote_id     NUMBER(19, 0) NOT NULL,
  motetype    VARCHAR(255)  NOT NULL,
  CONSTRAINT MOTETYPE_PK PRIMARY KEY (motetype_id),
  CONSTRAINT MOTE_M_FK FOREIGN KEY (mote_id) REFERENCES MOTE (mote_id)
);

CREATE SEQUENCE MOTEDELTAKER_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MOTEDELTAKER (
  motedeltaker_id   NUMBER(19, 0)       NOT NULL,
  motedeltaker_uuid VARCHAR(255) UNIQUE NOT NULL,
  motedeltakertype  VARCHAR(255)        NOT NULL,
  mote_id           NUMBER(19, 0)       NOT NULL,
  status            VARCHAR(255)        NOT NULL,
  svar_tidspunkt    TIMESTAMP,
  CONSTRAINT MOTEDELTAKER_PK PRIMARY KEY (motedeltaker_id),
  CONSTRAINT MOTE_MD_FK FOREIGN KEY (mote_id) REFERENCES MOTE (mote_id)
);

CREATE TABLE MOTEDELTAKER_ARBEIDSGIVER (
  motedeltaker_id NUMBER(19, 0) NOT NULL,
  navn            VARCHAR(255)  NOT NULL,
  epost           VARCHAR(255)  NOT NULL,
  CONSTRAINT MOTEDELTAKER_AG_PK PRIMARY KEY (motedeltaker_id),
  CONSTRAINT MOTEDELTAKER_AG_FK FOREIGN KEY (motedeltaker_id) REFERENCES MOTEDELTAKER (motedeltaker_id)
);

CREATE TABLE MOTEDELTAKER_AKTORID (
  motedeltaker_id NUMBER(19, 0) NOT NULL,
  aktor_id        VARCHAR(20)   NOT NULL,
  CONSTRAINT MOTEDELTAKER_AT_PK PRIMARY KEY (motedeltaker_id),
  CONSTRAINT MOTEDELTAKER_AT_FK FOREIGN KEY (motedeltaker_id) REFERENCES MOTEDELTAKER (motedeltaker_id)
);

CREATE TABLE AVSLAG (
  motedeltaker_id NUMBER(19, 0) NOT NULL,
  avviksaarsak    VARCHAR(255)  NOT NULL,
  CONSTRAINT MOTEDELTAKER_AVVIK_PK PRIMARY KEY (motedeltaker_id, avviksaarsak),
  CONSTRAINT MOTEDELTAKER_MA_FK FOREIGN KEY (motedeltaker_id) REFERENCES MOTEDELTAKER (motedeltaker_id)
);

CREATE SEQUENCE TID_STED_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TID_STED (
  tid_sted_id NUMBER(19, 0) NOT NULL,
  mote_id     NUMBER(19, 0) NOT NULL,
  tid         DATE          NOT NULL,
  sted        VARCHAR(255)  NOT NULL,
  CONSTRAINT TID_STED_PK PRIMARY KEY (tid_sted_id),
  CONSTRAINT MOTE_TS_FK FOREIGN KEY (mote_id) REFERENCES MOTE (mote_id)
);

CREATE TABLE MOTEDELTAKER_TID_STED (
  motedeltaker_id NUMBER(19, 0) NOT NULL,
  tid_sted_id     NUMBER(19, 0) NOT NULL,
  CONSTRAINT MOTEDELTAKER_TID_STED_PK PRIMARY KEY (motedeltaker_id, tid_sted_id),
  CONSTRAINT MOTEDELTAKER_MTS_MM_FK FOREIGN KEY (motedeltaker_id) REFERENCES MOTEDELTAKER (motedeltaker_id),
  CONSTRAINT TID_STED_MTS_MM_FK FOREIGN KEY (tid_sted_id) REFERENCES TID_STED (tid_sted_id)
);

ALTER TABLE MOTE
  ADD (
  CONSTRAINT TID_STED_M_FK FOREIGN KEY (valgt_tid_sted_id) REFERENCES TID_STED (tid_sted_id)
  );