-- ROLLBACK-START
------------------
-- ALTER TABLE MOTE
--   DROP COLUMN STATUS;
---------------
-- ROLLBACK-END

ALTER TABLE MOTE
  ADD (STATUS VARCHAR(255));

UPDATE MOTE SET
STATUS = 'OPPRETTET';

ALTER TABLE MOTE
  MODIFY STATUS NOT NULL;