-- ROLLBACK-START
------------------
-- DROP SEQUENCE HENDELSE_ID_SEQ;
-- DROP TABLE HENDELSE_MOTESTATUS_ENDRET;
-- DROP TABLE HENDELSE
---------------
-- ROLLBACK-END


CREATE SEQUENCE HENDELSE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE HENDELSE (
  HENDELSE_ID    NUMBER(19, 0) NOT NULL,
  inntruffetdato DATE          NOT NULL,
  type           VARCHAR(100)  NOT NULL,
  opprettet_av       VARCHAR(20)   NOT NULL,
  CONSTRAINT HENDELSE_PK PRIMARY KEY (HENDELSE_ID)
);


CREATE TABLE HENDELSE_MOTESTATUS_ENDRET (
  hendelse_id     NUMBER(19, 0) NOT NULL,
  status          VARCHAR(30)   NOT NULL,
  mote_id         NUMBER(19, 0) NOT NULL,
  CONSTRAINT HENDELSE_MSE_HENDELSE_FK FOREIGN KEY (hendelse_id) REFERENCES HENDELSE (HENDELSE_ID),
  CONSTRAINT HENDELSE_MSE_MOTE_FK FOREIGN KEY (mote_id) REFERENCES MOTE (MOTE_ID)
);