-- ROLLBACK-START
------------------
-- DROP SEQUENCE EPOST_ID_SEQ;
-- DROP SEQUENCE EPOST_VEDLEGG_ID_SEQ;
-- DROP TABLE EPOST
-- DROP TABLE EPOST_VEDLEGG
---------------
-- ROLLBACK-END


CREATE SEQUENCE EPOST_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EPOST_VEDLEGG_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE EPOST (
  epost_id    NUMBER(19, 0)   NOT NULL,
  mottaker    VARCHAR(100)    NOT NULL,
  emne        VARCHAR(100)    NOT NULL,
  innhold     VARCHAR(2000)   NOT NULL,
  sendt       NUMBER(1)       NOT NULL,
  CONSTRAINT EPOST_PK PRIMARY KEY (epost_id)
);

CREATE TABLE EPOST_VEDLEGG (
  epost_vedlegg_id    NUMBER(19, 0)   NOT NULL,
  epost_id            NUMBER(19, 0)   NOT NULL,
  innhold             VARCHAR(2000)   NOT NULL,
  type                VARCHAR(20)     NOT NULL,
  CONSTRAINT EPOST_FK FOREIGN KEY (epost_id) REFERENCES EPOST (epost_id),
  CONSTRAINT EPOST_VEDLEGG_PK PRIMARY KEY (epost_vedlegg_id)
);
