-- ROLLBACK-START
------------------
-- DROP TABLE HENDELSE_VARSEL_MOTEDELTAKER;
-- DROP TABLE HENDELSE_VARSEL_VEILEDER;
---------------
-- ROLLBACK-END

CREATE TABLE HENDELSE_VARSEL_MOTEDELTAKER (
  hendelse_id         NUMBER(19, 0) NOT NULL,
  motedeltaker_id     NUMBER(19, 0) NOT NULL,
  resultat            VARCHAR(100)  NOT NULL,
  adresse             VARCHAR(200),
  kanal               VARCHAR(30),
  varsel_type         VARCHAR(30)   NOT NULL,
  CONSTRAINT HENDELSE_HVM_HENDELSE_FK FOREIGN KEY (hendelse_id) REFERENCES HENDELSE (HENDELSE_ID),
  CONSTRAINT HENDELSE_HVM_MOTEDELTAKER_FK FOREIGN KEY (motedeltaker_id) REFERENCES MOTEDELTAKER (MOTEDELTAKER_ID)
);


CREATE TABLE HENDELSE_VARSEL_VEILEDER (
  hendelse_id         NUMBER(19, 0) NOT NULL,
  mote_id             NUMBER(19, 0) NOT NULL,
  veilederident       VARCHAR(20)   NOT NULL,
  kanal               VARCHAR(30)   NOT NULL,
  varsel_type         VARCHAR(30)   NOT NULL,
  CONSTRAINT HENDELSE_HVV_HENDELSE_FK FOREIGN KEY (hendelse_id) REFERENCES HENDELSE (HENDELSE_ID),
  CONSTRAINT HENDELSE_HVV_MOTE_FK FOREIGN KEY (mote_id) REFERENCES MOTE (MOTE_ID)
);